service:
  name: service-fraud-detection
image:
  repository: 952893849914.dkr.ecr.us-east-1.amazonaws.com/aicares-application/fraud-detection
containerPort: 8079
resources:
  limits:
    memory: "300Mi"
  requests:
    memory: "64Mi"
    cpu: "50m"
env:
  - name: FLAGD_HOST
    value: "flagd"
  - name: FLAGD_PORT
    value: "8013"
  - name: KAFKA_ADDR
    value: "kafka:9092"
  - name: OTEL_SERVICE_NAME
    value: "fraud-detection"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector:4317"
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
